name: Android CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Access GOOGLE_SERVICES_JSON
      env:
        APOD_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: Android Developer
        file: app/build/outputs/apk/release/app-release-unsigned.apk

